create table RE_LOCALIZACAO (id_localizacao_pai integer not null, id_localizacao_filha integer not null, primary key (id_localizacao_pai, id_localizacao_filha)) ENGINE=InnoDB
create table RE_LOCALIZACAO_AUD (REV integer not null, id_localizacao_pai integer not null, id_localizacao_filha integer not null, REVTYPE tinyint, primary key (REV, id_localizacao_pai, id_localizacao_filha)) ENGINE=InnoDB
create table REVINFO (REV integer not null auto_increment, REVTSTMP bigint, primary key (REV)) ENGINE=InnoDB
create table TB_AMARGOR (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, primary key (id)) ENGINE=InnoDB
create table TB_AUDITORIA_AMRAGOR (id integer not null, REV integer not null, REVTYPE tinyint, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_BAR (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), latitude decimal(20,8), longitude decimal(20,8), cep varchar(60), complemento varchar(60), logradouro varchar(250), numero varchar(60), observacaoEndereco varchar(1000), municipio_id integer, localizacao_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_BAR_CERVEJA (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, bar_id integer, cerveja_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_BAR_CERVEJA_RECEP_VOL (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, preco decimal(10,5), bar_cerveja_id integer, recepiente_volume_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_BAR_COMIDA (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), bar_id integer, comida_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_CERVEJA (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), teorAlcolico decimal(5,2), amargor_id integer, cervejaria_id integer, estilo_id integer, familia_id integer, pais_id integer, regiao_pais_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_CERVEJARIA (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), tipoCervejaria varchar(20), primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_CERVEJARIA_LOCALIZACAO (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), latitude decimal(20,8), longitude decimal(20,8), cep varchar(60), complemento varchar(60), logradouro varchar(250), numero varchar(60), observacaoEndereco varchar(1000), cervejaria_id integer, municipio_id integer, localizacao_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_COMIDA (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), comida_pai_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_CONTROLE_ENTIDADE (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), entidadeId integer, entidade varchar(255), primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_ENTIDADE (id varchar(255) not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, ordemPesquisa integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_ESTILO (id integer not null, REV integer not null, REVTYPE tinyint, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_FAMILIA (id integer not null, REV integer not null, REVTYPE tinyint, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_HARMONIZACAO (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), bar_comida_id integer, cerveja_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_LOCALIZACAO (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), latitude decimal(20,8), latitudeDelta decimal(20,8), longitude decimal(20,8), longitudeDelta decimal(20,8), primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_MUNICIPIO (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), codigoIBGE integer, localizacao tinyblob, uf_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_PAIS (id integer not null, REV integer not null, REVTYPE tinyint, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_PAIS_LOCALIZACAO (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), codigoIBGE integer, localizacao tinyblob, sigla varchar(255), primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_RECEPIENTE (id integer not null, REV integer not null, REVTYPE tinyint, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_RECEPIENTE_VOLUME (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, quantidade decimal(10,5), recepiente_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_REGIAO_PAIS (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), pais_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_TAG (id integer not null, REV integer not null, REVTYPE tinyint, primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_TIPO_LOCALIZACAO (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, classe varchar(250), nome varchar(250), primary key (id, REV)) ENGINE=InnoDB
create table TB_AUDITORIA_UF (id integer not null, REV integer not null, REVTYPE tinyint, ativo char(1), exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, nome varchar(250), texto varchar(1000), codigoIBGE integer, localizacao tinyblob, sigla varchar(255), pais_localizacao_id integer, primary key (id, REV)) ENGINE=InnoDB
create table TB_BAR (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, latitude decimal(20,8), longitude decimal(20,8), cep varchar(60), complemento varchar(60), logradouro varchar(250), numero varchar(60), observacaoEndereco varchar(1000), municipio_id integer not null, localizacao_id integer, primary key (id)) ENGINE=InnoDB
create table TB_BAR_CERVEJA (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, controleId integer not null, bar_id integer not null, cerveja_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_BAR_CERVEJA_RECEP_VOL (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, controleId integer not null, preco decimal(10,5), bar_cerveja_id integer not null, recepiente_volume_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_BAR_COMIDA (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, bar_id integer not null, comida_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_CERVEJA (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, teorAlcolico decimal(5,2), amargor_id integer not null, cervejaria_id integer not null, estilo_id integer not null, familia_id integer not null, pais_id integer not null, regiao_pais_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_CERVEJARIA (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, tipoCervejaria varchar(20) not null, primary key (id)) ENGINE=InnoDB
create table TB_CERVEJARIA_LOCALIZACAO (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, latitude decimal(20,8), longitude decimal(20,8), cep varchar(60), complemento varchar(60), logradouro varchar(250), numero varchar(60), observacaoEndereco varchar(1000), cervejaria_id integer not null, municipio_id integer not null, localizacao_id integer, primary key (id)) ENGINE=InnoDB
create table TB_COMIDA (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, comida_pai_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_CONTROLE_ENTIDADE (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250), texto varchar(1000), entidadeId integer not null, entidade varchar(255) not null, primary key (id)) ENGINE=InnoDB
create table TB_ENTIDADE (id varchar(255) not null, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, ordemPesquisa integer not null, primary key (id)) ENGINE=InnoDB
create table TB_ESTILO (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, primary key (id)) ENGINE=InnoDB
create table TB_FAMILIA (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, primary key (id)) ENGINE=InnoDB
create table TB_HARMONIZACAO (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, bar_comida_id integer not null, cerveja_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_LOCALIZACAO (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, latitude decimal(20,8), latitudeDelta decimal(20,8), longitude decimal(20,8), longitudeDelta decimal(20,8), primary key (id)) ENGINE=InnoDB
create table TB_MUNICIPIO (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, codigoIBGE integer not null, localizacao tinyblob not null, uf_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_PAIS (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, primary key (id)) ENGINE=InnoDB
create table TB_PAIS_LOCALIZACAO (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, codigoIBGE integer not null, localizacao tinyblob not null, sigla varchar(255) not null, primary key (id)) ENGINE=InnoDB
create table TB_RECEPIENTE (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, primary key (id)) ENGINE=InnoDB
create table TB_RECEPIENTE_VOLUME (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, quantidade decimal(10,5), recepiente_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_REGIAO_PAIS (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, pais_id integer not null, primary key (id)) ENGINE=InnoDB
create table TB_TAG (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, primary key (id)) ENGINE=InnoDB
create table TB_TIPO_LOCALIZACAO (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, classe varchar(250), nome varchar(250) not null, primary key (id)) ENGINE=InnoDB
create table TB_UF (id integer not null auto_increment, ativo char(1) not null, exclusao datetime, Inclusao datetime, ultimaAlteracao datetime, VERSAO bigint, nome varchar(250) not null, texto varchar(1000), controleId integer not null, codigoIBGE integer not null, localizacao tinyblob not null, sigla varchar(255) not null, pais_localizacao_id integer not null, primary key (id)) ENGINE=InnoDB
alter table TB_BAR_CERVEJA add constraint UKigo4cwxybpv8sb86nkoc2g3jg unique (cerveja_id, bar_id)
alter table TB_BAR_CERVEJA add constraint UK_8hg82sg0kld2u1n09soc0c94i unique (controleId)
alter table TB_BAR_CERVEJA_RECEP_VOL add constraint UK97wqxq5kx66g7l2gvbtuttgn7 unique (bar_cerveja_id, recepiente_volume_id)
alter table TB_BAR_CERVEJA_RECEP_VOL add constraint UK_p1n1gnjevgedgplsd981ajyt5 unique (controleId)
alter table TB_BAR_COMIDA add constraint UK93q02790j30890rkkgtugc5bj unique (comida_id, bar_id)
alter table TB_CONTROLE_ENTIDADE add constraint UKref9gdcyoguv17h5i6gu1bbem unique (entidade, entidadeId)
alter table TB_HARMONIZACAO add constraint UKku9t84t1117lr3179mn0li1pr unique (bar_comida_id, cerveja_id)
alter table RE_LOCALIZACAO add constraint FK7sgprg1sv5uoixyucp0vdx60d foreign key (id_localizacao_filha) references TB_LOCALIZACAO (id)
alter table RE_LOCALIZACAO add constraint FKrf3i0fc8tng4hs8otjvn2ww2n foreign key (id_localizacao_pai) references TB_LOCALIZACAO (id)
alter table RE_LOCALIZACAO_AUD add constraint FK9r4ca2v1wo96gihheipdqv016 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_AMRAGOR add constraint FKnic2xltjekoau0gsnsxvif6v1 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_BAR add constraint FKkiu59mgq0km7yjwnchbkvs790 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_BAR_CERVEJA add constraint FK663vsgy6wy6ywkf8wejro3tec foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_BAR_CERVEJA_RECEP_VOL add constraint FKk1r94o8gpsg57qnufhmgbw171 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_BAR_COMIDA add constraint FKlg7rg2fy01byi46qqqswmyoo2 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_CERVEJA add constraint FKi5mgb0xp2bas4ta317so06ffk foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_CERVEJARIA add constraint FKi77l3dkbvbtn0705fmfiduvyg foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_CERVEJARIA_LOCALIZACAO add constraint FK6bd53li9dtoko6px8rdd472cw foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_COMIDA add constraint FKkn1q4e7c1w98fc1ukctdbq6hq foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_CONTROLE_ENTIDADE add constraint FK8a9fjetln8ownollxo9g3anxq foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_ENTIDADE add constraint FK50dkptxbcktxnm7a49kfhq9rl foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_ESTILO add constraint FKp1l0xj6bfu37cahxu6tqg97lx foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_FAMILIA add constraint FK6dssmj87imai6gwrpc0t02to5 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_HARMONIZACAO add constraint FK594u2hj6gt1i7c2pmlltjinto foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_LOCALIZACAO add constraint FK3do8v06nisinaj925nsr42kdj foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_MUNICIPIO add constraint FKsggfn071hjjbwr190pyyc92xd foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_PAIS add constraint FK6ucvs2wxyfrc4tywkamcu0tu2 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_PAIS_LOCALIZACAO add constraint FKoh6y6fxe1h3for0lhuc9ol4ni foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_RECEPIENTE add constraint FKixssvmich65jn7nwexxguv7e7 foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_RECEPIENTE_VOLUME add constraint FKle31yqmmvjn8spg0qtxmbrdeb foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_REGIAO_PAIS add constraint FKlv16ux2i65o9t259btku8rpbi foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_TAG add constraint FKqqm6pi7cterfyy8h61j586ekx foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_TIPO_LOCALIZACAO add constraint FK70wk38mkqpm7eghs5kap1tlkt foreign key (REV) references REVINFO (REV)
alter table TB_AUDITORIA_UF add constraint FK8t0moa8gqp146unmj8753tokf foreign key (REV) references REVINFO (REV)
alter table TB_BAR add constraint FKkg3bnc98uipmyrojrwgc15vt5 foreign key (municipio_id) references TB_MUNICIPIO (id)
alter table TB_BAR add constraint FK86f7t97hh9kyi7nk98wjve9xj foreign key (localizacao_id) references TB_LOCALIZACAO (id)
alter table TB_BAR_CERVEJA add constraint FK5m4r65tll10r0emjxsr9anppg foreign key (bar_id) references TB_BAR (id)
alter table TB_BAR_CERVEJA add constraint FK76d32ypsnj3nxal8x8gpob1bb foreign key (cerveja_id) references TB_CERVEJA (id)
alter table TB_BAR_CERVEJA_RECEP_VOL add constraint FKkbvvgblbduxik0socddw01h9r foreign key (bar_cerveja_id) references TB_BAR_CERVEJA (id)
alter table TB_BAR_CERVEJA_RECEP_VOL add constraint FK3fc9ey7grao1ir2gnos9nihnr foreign key (recepiente_volume_id) references TB_RECEPIENTE_VOLUME (id)
alter table TB_BAR_COMIDA add constraint FKnp02mta8nl9hwx0gwc8xxlxwp foreign key (bar_id) references TB_BAR (id)
alter table TB_BAR_COMIDA add constraint FKb1bmfbvwbl3f11uyqv0qb5nlj foreign key (comida_id) references TB_COMIDA (id)
alter table TB_CERVEJA add constraint FK4ym6nrst52jjbgvjsgukaqbkl foreign key (amargor_id) references TB_AMARGOR (id)
alter table TB_CERVEJA add constraint FKjdvm5j12etonwfp5dws6pr3hc foreign key (cervejaria_id) references TB_CERVEJARIA (id)
alter table TB_CERVEJA add constraint FK9ch4ab6udb27yrpb339u2vk8c foreign key (estilo_id) references TB_ESTILO (id)
alter table TB_CERVEJA add constraint FKmhlfs0l9mns7ygtx6rbmdftl foreign key (familia_id) references TB_FAMILIA (id)
alter table TB_CERVEJA add constraint FKmispwq618ennioe9wt8hqnmu2 foreign key (pais_id) references TB_PAIS (id)
alter table TB_CERVEJA add constraint FK5uniikuajlhi43tsfgaqfgquw foreign key (regiao_pais_id) references TB_REGIAO_PAIS (id)
alter table TB_CERVEJARIA_LOCALIZACAO add constraint FK7ad9pnep1ac6f5bo17gd81c0h foreign key (cervejaria_id) references TB_CERVEJARIA (id)
alter table TB_CERVEJARIA_LOCALIZACAO add constraint FK8wv4wjg9ogwp5i81p8ft418pv foreign key (municipio_id) references TB_MUNICIPIO (id)
alter table TB_CERVEJARIA_LOCALIZACAO add constraint FKqjb4tcmawe5vo39eok37mhj4h foreign key (localizacao_id) references TB_LOCALIZACAO (id)
alter table TB_COMIDA add constraint FK4apt82hawvrh0v8pep79aljj0 foreign key (comida_pai_id) references TB_COMIDA (id)
alter table TB_CONTROLE_ENTIDADE add constraint FKrsh64j2uk5x1rx1m4bxkemjgd foreign key (entidade) references TB_ENTIDADE (id)
alter table TB_HARMONIZACAO add constraint FKae8j96qhero2etuha152af0qp foreign key (bar_comida_id) references TB_BAR_COMIDA (id)
alter table TB_HARMONIZACAO add constraint FK5eslbv1v7d9ub8l8l4gkhbtgh foreign key (cerveja_id) references TB_CERVEJA (id)
alter table TB_MUNICIPIO add constraint FKmv1s6iwcljblda7t85yyq128r foreign key (uf_id) references TB_UF (id)
alter table TB_RECEPIENTE_VOLUME add constraint FKny8jtm85qv9u37j5idcg229pp foreign key (recepiente_id) references TB_RECEPIENTE (id)
alter table TB_REGIAO_PAIS add constraint FKkb0aogr5dvdx1g1305yrhprg7 foreign key (pais_id) references TB_PAIS (id)
alter table TB_UF add constraint FK9e280mmuy7g5l3cmr3e9bh4ww foreign key (pais_localizacao_id) references TB_PAIS_LOCALIZACAO (id)
